# Generated by Django 5.2.6 on 2025-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('titulo', models.CharField()),
                ('descripcion', models.TextField()),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_recordatorio', models.DateTimeField()),
            ],
        ),
    ]
